import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from 'next-themes'
import { SWRProvider } from "@/provider/swr-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SWRProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider enableSystem={true} defaultTheme="light"
            disableTransitionOnChange attribute="class">
            {children}
          </ThemeProvider>
        </body>
      </html>
    </SWRProvider>
  );
}
